version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    staticcheck:
      checks:
        - "all"
        - "-ST1020"  # Don't require exported method comments to start with method name
        - "-ST1021"  # Don't require exported type comments to start with type name
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
