version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
    gosec:
      excludes:
        - G104  # Covered by errcheck
        - G101  # False positives on URL constants and test fixtures
        - G115  # Integer overflow: bounded by constants
        - G304  # File paths from config/env, not user input
    govet:
      enable-all: true
      disable:
        - fieldalignment
    staticcheck:
      checks:
        - "all"
        - "-ST1020"  # Don't require exported method comments to start with method name
        - "-ST1021"  # Don't require exported type comments to start with type name
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
